### ISSUE TITLE
issue when executing script

### ISSUE THREAD

**Issue by adorabletechguy** [azureinventory/ARI#11]
I was using this script without an issue for the last couple of weeks
I am not getting 
WARNING: Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
WARNING: Failed adding PivotTable 'P1': Index operation failed; the array index evaluated to null.
WARNING: Failed adding chart for pivotable 'P1': Cannot bind argument to parameter 'PivotTable' because it is null.
Report Complete. Total Runtime was: .4 Minutes

It appears that my tenantID isn't being populated also, regardless if I use the TenantID switch or not.

**Comment by knowlesy** [comment]
Can confirm I had the same issue when running as a RO user with the Global reader role, win 10 machine, and home 365 subscription for office .

**Comment by adorabletechguy** [comment]
Do you know what version of CLI and importexcel you're using/ i think im using the latest.

**Comment by adorabletechguy** [comment]
I tried a bunch of different version of this script, and installed lower versions of CLI and importexcel to no avail. I am not sure what happened.

**Comment by Mike-Ling** [comment]
Hi, first time user here... I hit the same issue:

The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107 char:17
+ ...               $Range.Style.HorizontalAlignment = $HorizontalAlignment
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17
+ ...             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

WARNING: Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
WARNING: Failed adding PivotTable 'P1': Index operation failed; the array index evaluated to null.
WARNING: Failed adding chart for pivotable 'P1': Cannot bind argument to parameter 'PivotTable' because it is null.
Report Complete. Total Runtime was: 1.2 Minutes
Total Resources: 0
Total Advisories:

ModuleType Version   Name
----------       -------    ----           
Script            7.1.2       ImportExcel

**Comment by adorabletechguy** [comment]
How i fixed it was: 
Changing :
`az extension add --name resource-graph` to `az extension add --name resource-graph --version 1.1.0`
and
`Install-Module -Name ImportExcel -Force` to `Install-Module -Name ImportExcel -RequiredVersion 7.1.2 -Force`

**Comment by Mike-Ling** [comment]
I only have version 7.1.2 of ImortExcel installed but the resource graph extension is 2.0.0:
{
    "experimental": false,
    "extensionType": "whl",
    "name": "resource-graph",
    "path": "C:\\Users\\xxx\\.azure\\cliextensions\\resource-graph",
    "preview": false,
    "version": "2.0.0"
 }
Downgrading to v1.1.0 does allow the script to complete. It does throw an error, but the Excel is generated:

ERROR: {
    "error": {
        "code": "BadRequest",
        "message": "Please provide below info when asking for support: timestamp = 2021-05-14T17:24:35.8232410Z, correlationId = 5261deb8-0879-401a-a414-b3304306421d.",
        "details": [
            {
                "code": "ResponsePayloadTooLarge",
                "message": "Response payload size is 35289540, and has exceeded the limit of 12582912. Please consider querying less data at a time and make paginated call if needed."
            }
        ]
    }
}

Changes to the resource graph extension seem to have broken things.

**Comment by adorabletechguy** [comment]
I ran az extension remove --name resource-graph and had the script reinstall it. I tested this theory but re running but upgrading importexcel and resource graph, Im not sure if it's worth noting, I am running the recent release of azcli

**Comment by ClaudioMerola** [comment]
Hi,

as mentioned by Mike-Ling in the #12 

Is possible this issue is related with the wrong identification of the script as CloudShell instead of Powershell Core.

I updated the script with Mike`s suggestion, can you guys try it and see how it goes?

Thanks

**Comment by adorabletechguy** [comment]
I tested the newest script, and i am getting the same errors I posted.

**Comment by ClaudioMerola** [comment]
Thanks for the answer adorabletechguy. I think I found the issue.

Newest version of Resource-Graph Extension present data in a different format. 

Can you try the 1.4.4?

Thanks

**Comment by adorabletechguy** [comment]
It executed without an errors.

**Comment by ClaudioMerola** [comment]
Good to know.
