### ISSUE TITLE
Get RESOURCES breaking change

### ISSUE THREAD

**Issue by salhidev** [azureinventory/ARI#135]
There was a change last week that breaks this part of script for version 3.0.0:

```
<######################################################### RESOURCES ######################################################################>


Write-Output ('Starting Resources Processes')

$ResourceJobs = 'Compute', 'Analytics', 'Containers', 'Data', 'Infrastructure', 'Integration', 'Networking', 'Storage'
$Modules = @()
Foreach ($Jobs in $ResourceJobs)
    {
        $OnlineRepo = Invoke-WebRequest -Uri ($Repo + '/' + $Jobs)
        $Modu = $OnlineRepo.Links | Where-Object { $_.href -like '*.ps1' }
        $Modules += $Modu.href
    }

foreach ($Module in $Modules) 
    {
        $SmaResources = @{}

        $Modul = $Module.split('/')
        $ModName = $Modul[7].Substring(0, $Modul[7].length - ".ps1".length)
        $ModuSeq = (New-Object System.Net.WebClient).DownloadString($RawRepo + '/Modules/' + $Modul[6] + '/' + $Modul[7])

        $ScriptBlock = [Scriptblock]::Create($ModuSeq)

        $SmaResources[$ModName] = Invoke-Command -ScriptBlock $ScriptBlock -ArgumentList $PSScriptRoot, $Subscriptions, $InTag, $Resources, 'Processing'

        Write-Output ('Resources ('+$ModName+'): '+$SmaResources[$ModName].count)

        Invoke-Command -ScriptBlock $ScriptBlock -ArgumentList $PSScriptRoot,$null,$InTag,$null,'Reporting',$File,$SmaResources,$TableStyle,$Unsupported | Out-Null

    }
```
This was working fine until last week. I just got the latest version and had to modify it to fit my business needs.
So just FYI, version 3.0.0 is breaking.

**Comment by Claudio-Merola** [comment]
Hi @salhidev 

But the script is at the version 3.2. Have you downloaded the last version? And it still had the issue?

**Comment by salhidev** [comment]
I don't see any problems with 3.2
But doesn't the prior version need to work as well ?
If not, is there a way to notify us that there is a breaking change and we need to update our versions ?

**Comment by Claudio-Merola** [comment]
Actually older versions should work as well. 
This particular update was related to Github. 

Essentially Github changed the way folders and files are listed in the browser. Since you were running the script with the -Online parameter, the "Invoke-WebRequest" command will behave exactly like the browser, and due to that Github change, the older versions of the script were not able to correctly list the resource modules.

So in this specific case, downloading the newer version of the script was the only way to solve that.
