### ISSUE TITLE
 Automate from Azure using Automation Accounts

### ISSUE THREAD

**Issue by camilohtaborda** [azureinventory/ARI#8]
Hi, I would like to know if there is a way to automate this script to obtain a daily inventory at a specific time in order to later generate history graphs.

**Comment by ClaudioMerola** [comment]
Hi, 

This is kinda tricky, the short answer is no 

Mainly because of the ImportExcel module, and because the script is using az cli. 

But with alot of customization, it would be possible to change the extraction to use Azure Powershell Module, and maybe save the results in a XML file in a Storage Account, and then run another script to merge all the data in a single spreadsheet. But that would be a complete new script.
