### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gjongeneel** [azureinventory/ARI#9]
A very big shout out to begin with. Very nice and useful script! Thanks! My remarks below are not really issues, more questions / feature requests. 

As a feature request, I would kindly ask for the inclusion of the 'new' Azure stuff like Functions Apps, Logic App, API Connections etc. 

And for the Azure Advisor part (which is already included, but a basic level), it would be nice to have for instance the savings per year (reservations etc.) included.

How is the 'Advisory score' calculated at the first page of the Excel sheet? It doesn't seem to corelate with any item within the portal. It's something different from the Advisor Score (Preview) or Secure Score. Where does this originate from?

**Comment by ClaudioMerola** [comment]
Hi, 

Thanks. 

We are including the other resources like Function Apps, Logic Apps etc. on new releases of the script, but some resources might take some time due to the complexity of how data is stored in Azure.

Regarding the Annual Savings of the Azure Advisor, to be able to extract details of every resource in the subscription, we are using the Azure Resource Graph, but not all information that is presented in the portal is available in the Azure Resource Graph. 

That’s why the score in the advisor spreadsheet is different from the score in the portal (the most likely is to remove the score from the spreadsheet in the next release of the script).

The same apply to the cost savings in the portal, some of the data come in the resource graph, but most not. To avoid present it wrongly in the spreadsheet we chose to not bring it at all. 

We are working in the Azure Cost Inventory script (https://github.com/azureinventory/ACI ), since the way we are extracting the information is very different in that script, is very likely to have the savings, annual savings, etc. in that script.

**Comment by gjongeneel** [comment]
Thanks for the feedback. I'm looking forward to the future additions!

I understand the limitations of Azure Resource Graph and I agree that showing the score does lead to some discussion as it does not seem to be consistent. 

Based on your suggestion about the other (Cost Inventory script), I checked that one out as well. But at this stage, It did not seem to work for me. I opened an issue to give my input at that specific GitHub space. I really appreciate your efforts to create these kinds of scripts.
